version: '3'

services:
  sleek-airflow:
    image: apache/airflow

    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"

    command: airflow standalone

# version: '3'

# services:
#   sleek-airflow:
#     build: 
#       context: . 
#       dockerfile: Dockerfile
#     volumes:
#       - ./airflow:/opt/airflow
#     ports:
#       - "8080:8080"
#     command: airflow standalone

