stages:
  collect_data:
    cmd: python data_collection.py
    outs:
      - raw_data.csv

  preprocess_data:
    cmd: python preprocessing.py
    deps:
      - raw_data.csv
    outs:
      - processed_data.csv

  train_model:
    cmd: python train_model.py
    deps:
      - processed_data.csv
    outs:
      - model.pkl